name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        shell: bash
        run: |
          echo "event=${{ github.event_name }}"
          echo "repo=${{ github.repository }}"
          echo "pr=${{ github.event.pull_request.number }}"

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Fetch agent source
        shell: bash
        run: |
          set -e
          git clone --depth 1 --branch main https://github.com/Adityan-78/pr-review-agent-supreme agent_src
          echo "PYTHONPATH=$GITHUB_WORKSPACE/agent_src" >> "$GITHUB_ENV"

      - name: Install deps
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r agent_src/requirements.txt
          pip install flake8 bandit pyyaml

      - name: Run agent
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          python -m agent.cli analyze --provider github --repo "${{ github.repository }}" --pr "${{ github.event.pull_request.number }}"
